### ISSUE TITLE
Method not found: 'Void Npgsql.NpgsqlBinaryImporter.Complete()'

### ISSUE THREAD

**Issue by FerdinandoCavaliere** [serilog-contrib/Serilog.Sinks.Postgresql.Alternative#72]
I've replaced the Serilog.Sinks.PostgreSQL sink with Serilog.Sinks.Postgresql.Alternative but I'm getting the following error

2024-06-17T08:15:55.0713830Z PeriodicBatchingSink (Serilog.Sinks.PostgreSQL.PostgreSQLSink): failed emitting a batch
System.MissingMethodException: Method not found: 'Void Npgsql.NpgsqlBinaryImporter.Complete()'.
   at Serilog.Sinks.PostgreSQL.PostgreSQLSink.ProcessEventsByCopyCommand(IEnumerable`1 events, NpgsqlConnection connection)
   at Serilog.Sinks.PostgreSQL.PostgreSQLSink.EmitBatch(IEnumerable`1 events)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.EmitBatchAsync(IEnumerable`1 events)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.LoopAsync()

The nuget  packages are:

PackageReference Include="Npgsql" Version="8.0.3" 
PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" 
PackageReference Include="Serilog" Version="4.0.0" 
PackageReference Include="Serilog.AspNetCore" Version="8.0.1" 
PackageReference Include="Serilog.Expressions" Version="5.0.0" 
PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" 
PackageReference Include="Serilog.Formatting.Elasticsearch" Version="10.0.0" 
PackageReference Include="Serilog.Settings.Configuration" Version="8.0.1" 
PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" 
PackageReference Include="Serilog.Sinks.PostgreSQL.Configuration" Version="1.0.1" 
PackageReference Include="Serilog.Sinks.Postgresql.Alternative" Version="4.0.4" 

All packages are updated

I use a configuration file

{
  "Serilog": {
    "Using": [
      "Serilog.Sinks.Console",
      "Serilog.Sinks.PostgreSQL.Configuration",
      "Serilog.Formatting.Elasticsearch",
      "Serilog.Expressions"
    ],
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft.EntityFrameworkCore": "Warning",
        "Microsoft": "Warning",
        "System": "Warning"
      }
    },
    "Enrich": [ "WithMachineName" ],
    "WriteTo": [
      {
        "Name": "PostgreSQL",
        "Args": {
          "connectionString": "PostgresConnection",
          "tableName": "\"LogUIConfigurator\"",
          "needAutoCreateTable": true,
          "columnOptionsSection": {
            "removeStandardColumns": [ "message_template", "machine_name" ]
          }
        }
      },
      {
        "Name": "Console",
        "Args": {
          "formatter": "Serilog.Formatting.Elasticsearch.ElasticsearchJsonFormatter, Serilog.Formatting.Elasticsearch"
        }
      }
    ]
  },
  "Columns": {
    "message": "RenderedMessageColumnWriter",
    "level": {
      "Name": "LevelColumnWriter",
      "Args": {
        "renderAsText": true,
        "dbType": "Varchar"
      }
    },
    "created_date": "TimestampColumnWriter",
    "exception": "ExceptionColumnWriter",
    "properties": "LogEventSerializedColumnWriter",
    "parameter_input": {
      "Name": "SinglePropertyColumnWriter",
      "Args": {
        "propertyName": "parameter_input",
        "writeMethod": "Json"
      }
    },
    "parameter_output": {
      "Name": "SinglePropertyColumnWriter",
      "Args": {
        "propertyName": "parameter_output",
        "writeMethod": "Raw"
      }
    },
    "user_logged_in": {
      "Name": "SinglePropertyColumnWriter",
      "Args": {
        "propertyName": "user_logged_in",
        "writeMethod": "Raw"
      }
    }
  }
}

The log table is created but the logs are not written

**Comment by FerdinandoCavaliere** [comment]
Resolved. Config file format was Serilog.Sinks.PostgreSQL style and not Serilog.Sinks.Postgresql.Alternative style
